dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - mysql
#before_install:
#  - cp .travis.settings.xml $HOME/.m2/settings.xml
before_script:
  - mysql -u root -e 'CREATE DATABASE desapp;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

#deploy:
#  provider: script
#  script: "mvn -B -V deploy"
#  skip_cleanup: true